pipeline {
    agent {
        label 'admin'
    }
    parameters {
        string(name: 'PROXMOX_IP', defaultValue: 'cyberops2.pizzasec.com', description: 'ProxMox IP address')
        string(name: 'PROXMOX_NODE', defaultValue: 'cyberops2', description: 'ProxMox to upload to')
        string(name: 'ISO_URL', defaultValue: '', description: 'URL of the ISO to download')
    }
    environment {
        PROXMOX_API_CREDS = credentials('proxmox-api-token')
    }
    stages {
        stage('Parameter Validation') {
            steps {
                script {
                    if (!params.ISO_URL) {
                        error("ISO URL parameter cannot be empty.")
                    }
                }
            }
        }
        
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/master']],
                    userRemoteConfigs: [[url: 'https://github.com/OrangeSquirter/homelab-seed.git']]
                ])
            }
        }

        stage('Download and Upload ISO') {
            agent {
                label 'admin'
            }
            stages {
                stage ('Execute within docker'){
                    agent {
                        dockerfile {
                            filename 'pipelines/download-iso/Dockerfile'
                        }
                    }
                    steps {
                        script {
                            dir('pipelines/download-iso') {
                                def token_name = PROXMOX_API_CREDS.split(':')[0]
                                def token_secret = PROXMOX_API_CREDS.split(':')[1]
                                sh """
                                    python download.py \
                                        --proxmox_ip    ${params.PROXMOX_IP} \
                                        --proxmox_node  ${params.PROXMOX_NODE} \
                                        --iso_url       ${params.ISO_URL} \
                                        --token_name    ${token_name} \
                                        --token_secret  ${token_secret}
                                """
                            }
                        }
                    }
                }
            }
        }
    }
}
