pipeline {
    agent {
        label 'main'
    }
    parameters {
        string(name: 'REPO_URL', defaultValue: 'https://github.com/your-repo/your-repo.git', description: 'Path to the repo')
        string(name: 'BAKE_FILE_PATH', defaultValue: "path/to/docker-bake.hcl", description: 'Path to docker bake file')
    }
    environment {
        REGISTRY = "192.168.1.100:5000"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git url: "${params.REPO_URL}"
            }
        }

        stage('Build Docker Images using docker-bake.hcl') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-registry-creds', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh "echo ${DOCKER_PASSWORD} | docker login ${REGISTRY} --username ${DOCKER_USERNAME} --password-stdin"
                    }
                    sh 'ls -la'
                    
                    sh 'docker buildx create --use || true'
                    sh "docker buildx bake -f ${params.BAKE_FILE_PATH}"
                }
            }
        }

        stage('Push Images to Registry') {
            steps {
                script {
                    sh "docker buildx bake -f ${params.BAKE_FILE_PATH} --push"
                }
            }
        }
    }

    post {
        success {
            echo 'Docker images built and pushed successfully!'
        }
        failure {
            echo 'Build failed. Check logs for errors.'
        }
    }
}
