pipeline {
    agent any
    
    environment {
        JENKINS_CREDENTIAL_ID = 'JENKINS_CREDENTIALS'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/master']],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    userRemoteConfigs: [[url: 'https://github.com/OrangeSquirter/homelab-seed.git']]
                ])
            }
        }
        
        stage('Create Jenkins API token') {
            steps {
                withCredentials([usernamePassword(credentialsId: env.JENKINS_CREDENTIAL_ID, usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    script {
                        def userName = 'jenkins'
                        def user = Jenkins.instance.getUser(userName)
                        
                        def generatedToken = user.getApiToken()
                        
                        withCredentials([string(credentialsId: env.JENKINS_CREDENTIAL_ID, secretValue: generatedToken)]) {
                            sh 'echo "Saved credentials"'
                        }
                    }
                }
            }
        }
    }
}
