pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/master']],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    userRemoteConfigs: [[url: 'https://github.com/OrangeSquirter/homelab-seed.git']]
                ])
            }
        }
        
        stage('Create Jenkins API token') {
            steps {
                script {
                    def userName = 'jenkins'
                    def tokenName = 'JENKINS_CREDENTIAL_ID'
                    
                    def user = Jenkins.instance.getUser(userName)
                    def apiTokenProperty = user.getProperty(ApiTokenProperty.class)
                    def generatedToken = apiTokenProperty.tokenStore.generateNewToken(tokenName)
                    
                    withCredentials([string(credentialsId: tokenName, secretValue: generatedToken.plainValue)]) {
                        // For example:
                        sh 'echo "Saved credentials"'
                    }
                    user.save()
                }
            }
        }
    }
}
