pipeline {
    agent {
        dockerfile {
            filename 'pipelines/jenkins-agent-builder/Dockerfile'
        }
    }
    options {
        disableConcurrentBuilds()
    }
    parameters {
        string(name: 'PROXMOX_IP', defaultValue: 'cyberops2.pizzasec.com', description: 'ProxMox IP address')
        string(name: 'PROXMOX_NODE', defaultValue: 'cyberops2', description: 'ProxMox to build the box on')
        string(name: 'PROXMOX_POOL', defaultValue: 'Admin', description: 'ProxMox resource pool to assign')
        string(name: 'TEMPLATE', defaultValue: 'ubuntu-22', description: 'Name of the template to use')
        choice(name: 'CORES', choices: ['2', '4', '8'], description: 'Number of cores that will be allocated to the VM')
        choice(name: 'MEMORY', choices: ['2048', '4096', '8192'], description: 'Memory allocation for the VM in MB')
        string(name: 'STORAGE', defaultValue: '20', description: 'Storage for the VM in GB')
        string(name: 'VM_NAME', defaultValue: 'jenkins-agent', description: 'Name of the box to build')
        string(name: 'ROLE', defaultValue: 'jenkins', description: 'Why is this box being built')
        string(name: 'BRANCH', defaultValue: 'master', description: 'If this is associated with a git branch, assign it')
        choice(name: 'NETWORK', choices: ['vmbr0', 'vmbr1', 'patron'], description: 'Network to place the VM on')
    }
    environment {
        PROXMOX_API_CREDS   = credentials('proxmox-api-token')
        PROXMOX_LOW_VMID    = "400"
        PROXMOX_HIGH_VMID   = "600"
    }
    stages {
        stage('Parameter Validation') {
            steps {
                script {
                    if (!params.ROLE.matches('^[a-zA-Z0-9._/-]+$')) {
                        error("Invalid ROLE parameter. Only letters, numbers, '.', '_', '-', and '/' are allowed.")
                    }
                    if (!params.BRANCH.matches('^[a-zA-Z0-9._/-]+$')) {
                        error("Invalid BRANCH parameter. Only letters, numbers, '.', '_', '-', and '/' are allowed.")
                    }
                    if (!params.STORAGE.isInteger() || params.STORAGE.toInteger() > 200) {
                        error("Invalid STORAGE parameter. It must be a number and less than or equal to 200.")
                    }
                }
            }
        }
        
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/master']],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    userRemoteConfigs: [[url: 'https://github.com/OrangeSquirter/homelab-seed.git']]
                ])
            }
        }
        
        stage('Build Box') {
            steps {
                script {
                    def buildbox = build job: 'box-builder', 
                        parameters: [
                            string(name: 'PROXMOX_IP',      value: params.PROXMOX_IP),
                            string(name: 'PROXMOX_NODE',    value: params.PROXMOX_NODE),
                            string(name: 'PROXMOX_POOL',    value: params.PROXMOX_POOL),
                            string(name: 'TEMPLATE',        value: params.TEMPLATE),
                            string(name: 'CORES',           value: params.CORES),
                            string(name: 'MEMORY',          value: params.MEMORY),
                            string(name: 'STORAGE',         value: params.STORAGE),
                            string(name: 'VM_NAME',         value: params.VM_NAME),
                            string(name: 'ROLE',            value: params.ROLE),
                            string(name: 'BRANCH',          value: params.BRANCH),
                            string(name: 'NETWORK',         value: params.NETWORK)
                        ], 
                        propagate: true, 
                        wait: true

                    copyArtifacts(
                        projectName: 'box-builder', 
                        selector: specific("${buildbox.number}"),
                        filter: 'vm_metadata.json'
                    )
                }
            }
        }
    }
}
