pipeline {
    agent admin
    parameters {
        string(name: 'PROXMOX_IP', defaultValue: 'cyberops2.pizzasec.com', description: 'ProxMox IP address')
        string(name: 'VMID', defaultValue: '0', description: 'VMID of VM to delete')
    }
    environment {
        PROXMOX_API_CREDS   = credentials('proxmox-api-token')
        PROXMOX_LOW_VMID    = "400"
        PROXMOX_HIGH_VMID   = "600"
    }
    stages {
        stage('Parameter Validation') {
            steps {
                script {
                    if (!params.ROLE.matches('^[0-9]+$')) {
                        error("Invalid VMID parameter. Only  numbers are allowed.")
                    }
                }
            }
        }
        
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/master']],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    userRemoteConfigs: [[url: 'https://github.com/OrangeSquirter/homelab-seed.git']]
                ])
            }
        }
        
        stage('Terminate Box') {
            stages {
                stage ('Execute within docker'){
                    agent {
                        dockerfile {
                            filename 'pipelines/box-terminator/Dockerfile'
                        }
                    }
                    steps {
                        script {
                            dir('pipelines/box-terminator') {
                                def token_name = PROXMOX_API_CREDS.split(':')[0]
                                def token_secret = PROXMOX_API_CREDS.split(':')[1]
                                sh """
                                    echo "Build a VM"
                                    python box-terminator.py \
                                        --proxmox_ip    ${params.PROXMOX_IP} \
                                        --vmid          ${params.VMID} \
                                        --token_name    ${token_name} \
                                        --token_secret  ${token_secret}
                                """
                            }
                        }
                    }
                }
            }
        }
    }
}
